# Time intervals
tints:
  # Flapping time interval
  flapping: ["2019-09-14T07:54:00.000", "2019-09-14T08:11:00.000"]
  # Close-up time interval
  close-up: ["2019-09-14T08:00:00.000", "2019-09-14T08:01:00.000"]

data_path: "/Users/louisr/Documents/PhD/Y1/flapping/data"

# Flux Gate Magnetometer parameters
fgm:
  # Flux Gate Magnetometer data rate
  data_rate: "srvy"
  # Flux Gate Magnetometer data level
  level: "l2"

# Electric Double Probe parameters
edp:
  # Electric Double Probe data rate
  data_rate: "fast"
  # Electric Double Probe data level
  level: "l2"

# Fast Plasma Investigation parameters
fpi:
  # Fast Plasma Investigation data rate
  data_rate: "fast"
  # Fast Plasma Investigation data level
  level: "l2"
  # Moments type
  moments: "partial"
  # Ion partial moment split index
  part_idx_i: 19
  # Electron partial moment split index
  part_idx_e: 7

# Figure parameters
figure:
  main:
    # Figure size
    figsize: [6.5, 9]

  # Grid spec parameters
  gridspec:
    # Left bound
    left: 0.15
    # Right bound
    right: 0.85
    # Bottom bound
    bottom: 0.05
    # Top bound
    top: 0.95
    # vertical space
    hspace: 0.13

  # Legend parameters
  legend:
    # Number of columns in the legend box
    ncol: 4
    # Frame
    frameon: True
    # Legend position
    loc: "upper right"

  # Save parameters
  save:
    # DPI
    dpi: 500